import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import '../../styles/hero.sass';

const Hero = props => {
  return (
    <div
        id={props.id}
        style={
          props.bg.color ?
            Object.assign({ background: props.bg.color }, props.style)
          : props.style
        }
        className={classNames(
          'hero',
          props.bg.gradient ? `lg-${props.bg.gradient}` : null,
          `justify-content-${props.align}`,
          `text-${props.align}`,
          `elevation-${props.elevation}`
    )}>
      <div>
        <div className="tagline">{props.tagline}</div>
        <h1>{props.title}</h1>
        <p>{props.paragraph}</p>
      </div>
    </div>
  )
};

Hero.propTypes = {
  align: PropTypes.oneOf(["left","center","right"]),
  /*
   * Additional custom class names for the hero
   */
  className: PropTypes.oneOfType([
    PropTypes.array,
    PropTypes.object,
    PropTypes.string,
  ]),
  elevation: PropTypes.number,
  /*
 * Unique id for the hero. Autogenerated if empty.
 */
  id: PropTypes.string,
  /*
 *  Additional overrideable styles for the hero
 */
  style: PropTypes.object,
  /*
  *  Background for the hero area
  */
  bg: PropTypes.shape({
    gradient: PropTypes.string,
    color: PropTypes.string
  }),
  /*
  *  Tagline for the hero
  */
  tagline: PropTypes.string,
  /*
  *  Title for the hero
  */
  title: PropTypes.string,
  /*
  *  Descriptive paragraph for the hero
  */
  paragraph: PropTypes.string,
};

export default Hero;